#!/bin/bash

shopt -qs extglob

# bpm's main code

autoupdate=1
[[ ! -e "$HOME"/.bpm ]] && mkdir "$HOME/.bpm" && "$repo/install"

if (( autoupdate )); then
	if [[ -e "$HOME/repos/bpm" ]]; then
		local repo="$HOME/repos/bpm"
	else
		local repo="$(find "$HOME" -type d -name bpm 2>/dev/null)"
	fi
	# Check for updates
	if [[ -n "$(diff "$repo"/.bpm/.lib "$HOME"/.bpm/.lib)" || -n "$(diff "$repo"/.bpm/help "$HOME"/.bpm/help)" || -n "$(diff "$repo"/.bpm/version "$HOME"/.bpm/version)" || -n "$(diff "$repo"/bpm "$HOME"/bin/bpm)" ]]; then
		"$repo/install"
	fi
fi
# Check for unit test
if [[ "$BPM_TST" == "true" ]]; then
	# Load the lib from the repo and set prgroot to repo
	echo -e "[BPM] UNIT TEST MODE! READING FROM REPO!"
	source "$repo"/.bpm/.lib
	prgroot="$repo/.bpm"
else
	source "$HOME"/.bpm/.lib
fi


__bpm() {
	if [[ -z "$1" ]]; then
		__args
	else
		if [[ "$1" =~ "-" ]]; then
			# Arg mode
			__args "$@"
		elif [[ "$1" =~ ${lists[cmds]} ]]; then
			# Command mode
			__cmds "$@"
		else
			__short "$@"
		fi
	fi
	__proc
}

__bpm "$@"

# Cleanup for accidental sourcing
[[ "$$" -eq "$BASHPID" ]] && unset __bpm __args __cwd autoupdate repo prgroot __loadcfg __cfg error verbose log lists __cmds states
