#!/bin/bash

# bpm's installer
install() {
	local repo="$(find "$HOME" -type d -name bpm 2>/dev/null | grep repo)"
	
	# Preprocess
	[[ ! -e "$HOME/.bpm" ]] && mkdir "$HOME/.bpm" 2>/dev/null

	# Install
	cp -f "$repo"/bpm "$HOME"/bin || return 1
	cp -f "$repo"/.bpm/.lib "$HOME"/.bpm || return 1
	cp -f "$repo"/.bpm/help "$HOME"/.bpm || return 1
	cp -f "$repo"/.bpm/version "$HOME"/.bpm || return 1

	# Comment if you want quiet installation
	echo "bpm installed!"
}

install "$@"
